import type { Metadata } from "next";
<<<<<<< HEAD
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";

const jakarta = Plus_Jakarta_Sans({ 
  subsets: ["latin"], 
  variable: "--font-jakarta",
  weight: ['300', '400', '500', '600', '700', '800']
});

export const metadata: Metadata = {
  title: "NasDem Ciamis - Gerakan Perubahan",
  description: "Website Resmi DPD Partai NasDem Kabupaten Ciamis",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="id" className="scroll-smooth">
      {/* Menggunakan biru yang lebih sesuai dengan logo */}
      <body className={`${jakarta.variable} font-sans bg-[#19367F] min-h-screen text-white`}>
        <Navbar />
        
        {/* Main container tanpa shadow agar seamless di layar besar */}
        <main className="max-w-[1440px] mx-auto bg-[#19367F] min-h-screen relative">
          {children}
        </main>
      </body>
    </html>
  );
}
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
>>>>>>> bf0156d (Initial commit from Create Next App)
